### ISSUE TITLE
sometimes it crashes on start: FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by 532910** [m3sv/PlainUPnP#67]
```
29285 29302 I ActivityManager: Start proc 2037:com.m3sv.plainupnp/u0a270 for activity com.m3sv.plainupnp/.presentation.splash.SplashActivity
29285 29729 I ActivityManager: START u0 {cmp=com.m3sv.plainupnp/.presentation.main.MainActivity} from uid 10270
 2037  2037 E AndroidRuntime: FATAL EXCEPTION: main
 2037  2037 E AndroidRuntime: Process: com.m3sv.plainupnp, PID: 2037
 2037  2037 E AndroidRuntime: java.lang.IllegalArgumentException: Action can not be null
 2037  2037 E AndroidRuntime:   at org.fourthline.cling.model.action.ActionInvocation.<init>(Unknown Source:37)
 2037  2037 E AndroidRuntime:   at org.fourthline.cling.model.action.ActionInvocation.<init>(Unknown Source:1)
 2037  2037 E AndroidRuntime:   at org.fourthline.cling.support.contentdirectory.callback.Browse.<init>(Unknown Source:8)
 2037  2037 E AndroidRuntime:   at com.m3sv.plainupnp.upnp.e$a.<init>(Unknown Source:24)
 2037  2037 E AndroidRuntime:   at com.m3sv.plainupnp.upnp.e.b(Unknown Source:50)
 2037  2037 E AndroidRuntime:   at com.m3sv.plainupnp.upnp.d0.t(Unknown Source:18)
 2037  2037 E AndroidRuntime:   at com.m3sv.plainupnp.upnp.d0.a(Unknown Source:24)
 2037  2037 E AndroidRuntime:   at com.m3sv.plainupnp.upnp.s0.c.a(Unknown Source:7)
 2037  2037 E AndroidRuntime:   at com.m3sv.plainupnp.upnp.s0.c.e(Unknown Source:52)
 2037  2037 E AndroidRuntime:   at com.m3sv.plainupnp.presentation.main.k$e.d(Unknown Source:81)
 2037  2037 E AndroidRuntime:   at f.y.k.a.a.l(Unknown Source:8)
 2037  2037 E AndroidRuntime:   at kotlinx.coroutines.x0.b(Unknown Source:114)
 2037  2037 E AndroidRuntime:   at kotlinx.coroutines.d3.a.b(Unknown Source:15)
 2037  2037 E AndroidRuntime:   at kotlinx.coroutines.m0.a(Unknown Source:35)
 2037  2037 E AndroidRuntime:   at kotlinx.coroutines.a.K0(Unknown Source:3)
 2037  2037 E AndroidRuntime:   at kotlinx.coroutines.h.c(Unknown Source:22)
 2037  2037 E AndroidRuntime:   at kotlinx.coroutines.f.c(Unknown Source:0)
 2037  2037 E AndroidRuntime:   at kotlinx.coroutines.h.d(Unknown Source:12)
 2037  2037 E AndroidRuntime:   at kotlinx.coroutines.f.d(Unknown Source:0)
 2037  2037 E AndroidRuntime:   at com.m3sv.plainupnp.presentation.main.k.q(Unknown Source:19)
 2037  2037 E AndroidRuntime:   at com.m3sv.plainupnp.presentation.main.ControlsFragment$m.onItemClick(Unknown Source:13)
 2037  2037 E AndroidRuntime:   at android.widget.AutoCompleteTextView.performCompletion(AutoCompleteTextView.java:1017)
 2037  2037 E AndroidRuntime:   at android.widget.AutoCompleteTextView.access$500(AutoCompleteTextView.java:96)
 2037  2037 E AndroidRuntime:   at android.widget.AutoCompleteTextView$DropDownItemClickListener.onItemClick(AutoCompleteTextView.java:1313)
 2037  2037 E AndroidRuntime:   at android.widget.AdapterView.performItemClick(AdapterView.java:318)
 2037  2037 E AndroidRuntime:   at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
 2037  2037 E AndroidRuntime:   at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
 2037  2037 E AndroidRuntime:   at android.widget.AbsListView$3.run(AbsListView.java:4052)
 2037  2037 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:873)
 2037  2037 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:99)
 2037  2037 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:193)
 2037  2037 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:6718)
 2037  2037 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
 2037  2037 E AndroidRuntime:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 2037  2037 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
29285 29297 W ActivityManager:   Force finishing activity com.m3sv.plainupnp/.presentation.main.MainActivity
29285 29301 I ActivityManager: Showing crash dialog for package com.m3sv.plainupnp u0
29285 29300 W ActivityManager: Activity pause timeout for ActivityRecord{ef34446 u0 com.m3sv.plainupnp/.presentation.main.MainActivity t2492 f}
29285 32533 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10018?v=7&cv=9 pkg=com.google.android.googlequicksearchbox } U=0: not found
29285 29297 W ActivityManager:   Force finishing activity com.m3sv.plainupnp/.presentation.main.MainActivity
29285 29297 I ActivityManager: Killing 2037:com.m3sv.plainupnp/u0a270 (adj 50): crash
```

**Comment by m3sv** [comment]
Yeah, it's a known issue unfortunately. I'm currently investing what's wrong in there.

**Comment by m3sv** [comment]
Should be fixed https://github.com/m3sv/PlainUPnP/releases/tag/3.0.2.

Feel free to reopen in case it still crashes for you with the same exception.

Thanks!
