### ISSUE TITLE
Application crashes on GetPositionInfo

### ISSUE THREAD

**Issue by m3sv** [m3sv/PlainUPnP#90]
> Fatal Exception: java.lang.IllegalStateException: Failed to get position info
       at com.m3sv.plainupnp.upnp.actions.avtransport.GetPositionInfoAction$getPositionInfo$2$action$1.failure(GetPositionInfoAction.java:18)
       at org.fourthline.cling.controlpoint.ActionCallback.failure(ActionCallback.java:4)
       at org.fourthline.cling.controlpoint.ActionCallback.run(ActionCallback.java:94)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:784)

**Comment by m3sv** [comment]
Fixed in https://github.com/m3sv/PlainUPnP/releases/tag/3.0.2.
