### ISSUE TITLE
Crash when starting/stoppping media server

### ISSUE THREAD

**Issue by m3sv** [m3sv/PlainUPnP#91]
> Fatal Exception: java.net.SocketException: Socket closed
       at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:159)
       at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
       at java.net.ServerSocket.bind(ServerSocket.java:377)
       at java.net.ServerSocket.bind(ServerSocket.java:331)
       at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:43)
       at java.lang.Thread.run(Thread.java:923)

**Comment by m3sv** [comment]
Fixed in https://github.com/m3sv/PlainUPnP/releases/tag/3.0.2.
