### ISSUE TITLE
NPE when casting device to CDevice

### ISSUE THREAD

**Issue by m3sv** [m3sv/PlainUPnP#93]
> Fatal Exception: java.lang.NullPointerException: null cannot be cast to non-null type com.m3sv.plainupnp.upnp.CDevice
       at java.util.Objects.requireNonNull(Objects.java:228)
       at com.m3sv.plainupnp.upnp.manager.UpnpManagerImpl$safeNavigateTo$2.invokeSuspend(UpnpManagerImpl.java:95)
       at com.m3sv.plainupnp.upnp.manager.UpnpManagerImpl$safeNavigateTo$2.invoke(UpnpManagerImpl.java:8)
       at com.m3sv.plainupnp.upnp.manager.UpnpManagerImpl$safeNavigateTo$2.invoke(UpnpManagerImpl.java:4)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(UndispatchedKt.java:9)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(BuildersKt__Builders_commonKt.java:49)
       at kotlinx.coroutines.BuildersKt.withContext(BuildersKt.java)
       at com.m3sv.plainupnp.upnp.manager.UpnpManagerImpl$itemClick$2.invokeSuspend(UpnpManagerImpl.java:73)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:9)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:129)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java)

Seems like it's not returning when device is null.

**Comment by m3sv** [comment]
Fixed in https://github.com/m3sv/PlainUPnP/releases/tag/3.0.2.
