### ISSUE TITLE
Crash when emitting devices

### ISSUE THREAD

**Issue by m3sv** [m3sv/PlainUPnP#94]
> Fatal Exception: java.lang.NegativeArraySizeException: -1
       at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
       at java.util.ArrayList.<init>(ArrayList.java:191)
       at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(CollectionsKt___CollectionsKt.java:7)
       at kotlin.collections.CollectionsKt.toMutableList(CollectionsKt.java)
       at kotlin.collections.CollectionsKt___CollectionsKt.toList(CollectionsKt___CollectionsKt.java:21)
       at kotlin.collections.CollectionsKt.toList(CollectionsKt.java)
       at com.m3sv.plainupnp.upnp.discovery.device.ContentDirectoryDiscoveryObservable.getCurrentContentDirectories(ContentDirectoryDiscoveryObservable.java:2)
       at com.m3sv.plainupnp.upnp.discovery.device.ContentDirectoryDiscoveryObservable$invoke$1$callback$1.sendContentDirectories(ContentDirectoryDiscoveryObservable.java:12)
       at com.m3sv.plainupnp.upnp.discovery.device.ContentDirectoryDiscoveryObservable$invoke$1$callback$1.removedDevice(ContentDirectoryDiscoveryObservable.java:8)
       at com.m3sv.plainupnp.upnp.discovery.device.DeviceDiscovery.notifyRemoved(DeviceDiscovery.java:23)
       at com.m3sv.plainupnp.upnp.discovery.device.DeviceDiscovery.access$notifyRemoved(DeviceDiscovery.java)
       at com.m3sv.plainupnp.upnp.discovery.device.DeviceDiscovery$BrowsingRegistryListener.deviceRemoved(DeviceDiscovery.java:30)
       at com.m3sv.plainupnp.upnp.CRegistryListener.localDeviceRemoved(CRegistryListener.java:17)
       at org.fourthline.cling.registry.LocalItems$3.run(LocalItems.java:8)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by m3sv** [comment]
Fixed in https://github.com/m3sv/PlainUPnP/releases/tag/3.0.2.
